export const TOKENS = {
  ProductRepository: Symbol.for("ProductRepository"),
  CreateProduct: Symbol.for("CreateProduct"),
  GetAllProducts: Symbol.for("GetAllProducts"),
  InventoryPublicApi: Symbol.for("InventoryPublicApi"),
  TransactionRepository: Symbol.for("TransactionRepository"),
  CreateTransaction: Symbol.for("CreateTransaction"),
  GetAllTransactions: Symbol.for("GetAllTransactions"),
  SalesPublicApi: Symbol.for("SalesPublicApi"),
  CalculateProductForecast: Symbol.for("CalculateProductForecast"),
  AddStock: Symbol.for("AddStock"),
  UpdateProduct: Symbol.for("UpdateProduct"),
  DeleteProduct: Symbol.for("DeleteProduct"),
  UserRepository: Symbol.for("UserRepository"),
  AuthService: Symbol.for("AuthService"),
  RegisterUser: Symbol.for("RegisterUser"),
  LoginUser: Symbol.for("LoginUser"),
};
